Algoritmo "exercicio8"
// Descrição   : Conversão de graus em radianos (segundo função seno, cosseno e tangente)
// Autor(a)    : Gabriel Vieira Cardoso
// Data atual  : 13/01/2023

Var
   valorAnguloEmGraus, valorAnguloEmRadianos : real
   
Inicio
   escreva("Insira um valor de ângulo em graus: ")
   leia(valorAnguloEmGraus)
   
   valorAnguloEmRadianos <- valorAnguloEmGraus * 3.14/180;
   
   escreva("Esse ângulo em radianos equivale a: ",valorAnguloEmRadianos)

Fimalgoritmo