Algoritmo "operadoresExemplo"
// Descrição   : Programa para calcular a média entre dois números quaisquer
// Autor(a)    : Gabriel Vieira Cardoso
// Data atual  : 12/01/2023
Var
numero1: real
numero2: real
media: real

Inicio
      escreva("Digite o primeiro número: ")
      leia(numero1)
      escreva("Digite o segundo número: ")
      leia(numero2)
      media <- (numero1 + numero2)/2
      escreva(media)

Fimalgoritmo